const varieties = {
  fruit: {
    "Abricot": { "Rouge du Roussillon": 5, "Orangered": 6, "Goldrich": 7 },
    "Açaï": { "Nature": 15, "Lyophilisé": 20 },
    "Acerola": { "Nature": 18 },
    "Ananas": { "Cayenne lisse": 4, "Queen Victoria": 5, "Pain de sucre": 6 },
    "Avocat": { "Hass": 8, "Fuerte": 7 },
    "Baie de goji": { "Séchée": 12 },
    "Baies": { "Myrtilles": 8, "Framboises": 10, "Mûres": 9 },
    "Banane": { "Banane plantain": 2, "Cavendish": 3 },
    "Canistel": { "Nature": 14 },
    "Carambole": { "Classique": 6 },
    "Cerise": { "Griottes": 7, "Bigarreau": 8, "Napoléon": 9 },
    "Citron": { "Jaune": 3, "Vert": 4, "Feuille Italie": 5, "Feuille Portugal": 6, "Categorie 1": 7, "Catégorie 2": 8 },
    "Clémentine": { "Corse": 6, "Espagne": 5 },
    "Coing": { "Nature": 6 },
    "Datte": { "Deglet Nour": 6, "Medjool": 10 },
    "Durian": { "Classique": 30 },
    "Figue": { "Blanche": 6, "Noire": 7, "Violette": 6.5 },
    "Fruit de la passion": { "Classique": 9 },
    "Grenade": { "Mollar": 8 },
    "Goyave": { "Rose": 7, "Blanche": 6 },
    "Kiwi": { "Vert": 4, "Gold": 5 },
    "Litchi": { "Maurice": 7 },
    "Mangue": { "Kent": 7, "Tommy Atkins": 6, "Amélie": 8 },
    "Melon": { "Charentais": 5, "Canari": 4, "Galia": 4.5 },
    "Orange": { "Navel": 3, "Sanguine": 4, "Valencia": 5 },
    "Papaye": { "Solo": 6 },
    "Pastèque": { "Rouge": 4, "Jaune": 5, "Mini": 3.5 },
    "Pêche": { "Jaune": 6, "Blanche": 6, "Pavie": 7 },
    "Poire": { "Conférence": 5, "William": 6, "Comice": 7, "Louise Bonne": 5.5 },
    "Pomme": { "Golden": 3, "Granny Smith": 4, "Gala": 5, "Pink Lady": 6 },
    "Prune": { "Quetsche": 4, "Mirabelle": 5, "Reine-Claude": 6 },
    "Raisin": { "Blanc": 6, "Rouge": 7, "Noir": 8, "Chasselas": 6.5 }
  },
  legume: {
    "Artichaut": { "Camus": 3, "Violet de Provence": 4 },
    "Asperge": { "Verte": 6, "Blanche": 7, "Violette": 8 },
    "Aubergine": { "Noire": 3, "Blanche": 4, "Graffiti": 5 },
    "Betterave": { "Rouge": 2, "Jaune": 3, "Chioggia": 4 },
    "Brocoli": { "Calabrais": 3.5 },
    "Carotte": { "Nantaise": 2, "Chantenay": 3, "Touchon": 4 },
    "Céleri": { "Branche": 2, "Rave": 3 },
    "Chou": { "Rouge": 3, "Vert": 2, "Fleur": 4, "Kale": 5 },
    "Concombre": { "Noa": 2.5, "Hollandais": 3 },
    "Courge": { "Butternut": 4, "Potimarron": 5, "Spaghetti": 6 },
    "Courgette": { "Verte": 2, "Jaune": 3, "Ronde de Nice": 4 },
    "Épinard": { "Géant d'hiver": 3, "Monstrueux de Viroflay": 4, "Butterflay": 5 },
    "Haricot": { "Vert": 5, "Rouge": 6, "Blanc": 7 },
    "Laitue": { "Romaine": 2, "Batavia": 3, "Iceberg": 4 },
    "Navet": { "Blanc": 2, "Jaune": 3, "Rutabaga": 4 },
    "Oignon": { "Jaune": 1.5, "Rouge": 2, "Blanc": 2.5 },
    "Patate douce": { "Orange": 3, "Violette": 4 },
    "Poireau": { "Bleu de Solaise": 3, "Carentan": 2.8 },
    "Pomme de terre": { "Charlotte": 1.5, "Bintje": 1.8, "Ratte": 2, "Agata": 1.7 },
    "Radis": { "Rose": 1.2, "Noir": 1.5, "Blanc": 1.8 },
    "Tomate": { "Cœur de Bœuf": 6, "Roma": 5, "Cerise": 7, "Ananas": 6.5 }
  },
  condiment: {
    "Ail": { "Blanc": 3, "Noir": 5, "Des ours": 6 },
    "Aneth": { "Fraîche": 2 },
    "Basilic": { "Vert": 2, "Pourpre": 3 },
    "Ciboulette": { "Classique": 1.5 },
    "Coriandre": { "Fraîche": 1.5 },
    "Estragon": { "Classique": 2 },
    "Menthe": { "Poivrée": 2, "Verte": 2 },
    "Origan": { "Sec": 1.5 },
    "Persil": { "Plat": 1.5, "Frisé": 1.5 },
    "Romarin": { "Frais": 1.8 },
    "Sauge": { "Officinale": 2 },
    "Thym": { "Citron": 2, "Classique": 1.8 }
  },
  fruitSec: {
    "Amande": { "Grillé non salée": 10, "Grillée salée": 12, "Nature": 8, "Chocolat": 15, "Caramel": 14 },
    "Wasabi": { "Petits pois enrobés": 9 },
    "Cajou": { "Grillé non salée": 18, "Nature": 16, "Caramelisé": 19 },
    "Noix": { "Classique": 12, "Pécan": 20, "Brésil": 18, "Macadamia": 25, "Mélange étudiant": 15, "Mélange sportif": 17 },
    "Noisette": { "Grillé non salée": 13, "Nature": 11, "Chocolat": 16 },
    "Pistache": { "Grillé non salée": 22, "Grillée salée": 24 }
  },
  exotique: {
    "Bissap": { "Sec": 8 },
    "Carambole": { "Classique": 6 },
    "Corossol": { "Nature": 12 },
    "Durian": { "Classique": 30 },
    "Gombo": { "Frais": 4 },
    "Jacquier": { "Nature": 15 },
    "Kiwano": { "Classique": 15 },
    "Safou": { "Nature": 10 },
    "Tamarin": { "Sec": 9 },
    "Ugli": { "Classique": 7 }
  }
};
