const varieties = {
  fruit: {
    "Abricot": { "Rouge du Roussillon": 5, "Orangered": 6, "Goldrich": 7 },
    "Açaï": {},
    "Acerola": {},
    "Ananas": { "Cayenne lisse": 4, "Queen Victoria": 5 },
    "Avocat": {},
    "Baie de goji": {},
    "Baies": { "Myrtilles": 8, "Framboises": 10, "Mûres": 9 },
    "Banane": { "Banane plantain": 2 },
    "Canistel": {},
    "Carambole": {},
    "Cerise": { "Griottes": 7, "Bigarreau": 8, "Napoléon": 9 },
    "Citron": { "Jaune": 3, "Vert": 4, "Feuille Italie": 5, "Feuille Portugal": 6, "Categorie 1": 7, "Catégorie 2": 8 },
    "Clémentine": {},
    "Coing": {},
    "Datte": { "Deglet Nour": 6, "Medjool": 10 },
    "Durian": { "Classique": 30 },
    "Figue": { "Blanche": 6, "Noire": 7 },
    "Fruit de la passion": {},
    "Grenade": {},
    "Goyave": {},
    "Kiwi": { "Vert": 4, "Gold": 5 },
    "Litchi": {},
    "Mangue": { "Kent": 7, "Tommy Atkins": 6, "Amélie": 8 },
    "Melon": { "Charentais": 5, "Canari": 4 },
    "Orange": { "Navel": 3, "Sanguine": 4, "Valencia": 5 },
    "Papaye": {},
    "Pastèque": { "Rouge": 4, "Jaune": 5 },
    "Pêche": { "Jaune": 6, "Blanche": 6 },
    "Poire": { "Conférence": 5, "William": 6, "Comice": 7 },
    "Pomme": { "Golden": 3, "Granny Smith": 4, "Gala": 5 },
    "Prune": { "Quetsche": 4, "Mirabelle": 5, "Reine-Claude": 6 },
    "Raisin": { "Blanc": 6, "Rouge": 7, "Noir": 8 }
  },
  legume: {
    "Artichaut": {},
    "Asperge": { "Verte": 6, "Blanche": 7, "Violette": 8 },
    "Aubergine": { "Noire": 3, "Blanche": 4, "Graffiti": 5 },
    "Betterave": { "Rouge": 2, "Jaune": 3, "Chioggia": 4 },
    "Brocoli": {},
    "Carotte": { "Nantaise": 2, "Chantenay": 3, "Touchon": 4 },
    "Céleri": { "Branche": 2, "Rave": 3 },
    "Chou": { "Rouge": 3, "Vert": 2, "Fleur": 4 },
    "Concombre": {},
    "Courge": { "Butternut": 4, "Potimarron": 5, "Spaghetti": 6 },
    "Courgette": { "Verte": 2, "Jaune": 3, "Ronde de Nice": 4 },
    "Épinard": { "Géant d'hiver": 3, "Monstrueux de Viroflay": 4, "Butterflay": 5 },
    "Haricot": { "Vert": 5, "Rouge": 6, "Blanc": 7 },
    "Laitue": { "Romaine": 2, "Batavia": 3, "Iceberg": 4 },
    "Navet": { "Blanc": 2, "Jaune": 3, "Rutabaga": 4 },
    "Oignon": { "Jaune": 1.5, "Rouge": 2, "Blanc": 2.5 },
    "Patate douce": { "Orange": 3, "Violette": 4 },
    "Poireau": {},
    "Pomme de terre": { "Charlotte": 1.5, "Bintje": 1.8, "Ratte": 2 },
    "Radis": { "Rose": 1.2, "Noir": 1.5, "Blanc": 1.8 },
    "Tomate": { "Cœur de Bœuf": 6, "Roma": 5, "Cerise": 7 }
  },
  condiment: {
    "Ail": { "Blanc": 3, "Noir": 5, "Des ours": 6 },
    "Aneth": {},
    "Basilic": { "Vert": 2, "Pourpre": 3 },
    "Ciboulette": {},
    "Coriandre": {},
    "Estragon": {},
    "Menthe": { "Poivrée": 2, "Verte": 2 },
    "Origan": {},
    "Persil": { "Plat": 1.5, "Frisé": 1.5 },
    "Romarin": {},
    "Sauge": {},
    "Thym": { "Citron": 2, "Classique": 1.8 }
  },
  fruitSec: {
    "Amande": { "Grillé non salée": 10, "Grillée salée": 12, "Nature": 8, "Chocolat": 15, "Caramel": 14 },
    "Wasabi": {},
    "Cajou": { "Grillé non salée": 18, "Nature": 16 },
    "Noix": { "Classique": 12, "Pécan": 20, "Brésil": 18, "Macadamia": 25, "Mélange étudiant": 15, "Mélange sportif": 17 },
    "Noisette": { "Grillé non salée": 13, "Nature": 11 },
    "Pistache": { "Grillé non salée": 22, "Grillée salée": 24 }
  },
  exotique: {
    "Bissap": {},
    "Carambole": {},
    "Corossol": {},
    "Durian": { "Classique": 30 },
    "Gombo": {},
    "Jacquier": {},
    "Kiwano": { "Classique": 15 },
    "Safou": {},
    "Tamarin": {},
    "Ugli": {}
  }
};
