const varieties = {
      fruit: {
        "Abricot": ["Rouge du Roussillon", "Orangered", "Goldrich"],
        "Açaï": [],
        "Acerola": [],
        "Ananas": ["Cayenne lisse", "Queen Victoria"],
        "Avocat": [],
        "Baie de goji": [],
        "Baies": ["Myrtilles", "Framboises", "Mûres"],
        "Banane": ["Banane plantain"],
        "Canistel": [],
        "Carambole": [],
        "Cerise": ["Griottes", "Bigarreau", "Napoléon"],
        "Citron": ["Jaune", "Vert"],
        "Clémentine": [],
        "Coing": [],
        "Datte": ["Deglet Nour", "Medjool"],
        "Durian": [],
        "Figue": ["Blanche", "Noire"],
        "Fruit de la passion": [],
        "Grenade": [],
        "Goyave": [],
        "Kiwi": ["Vert", "Gold"],
        "Litchi": [],
        "Mangue": ["Kent", "Tommy Atkins", "Amélie"],
        "Melon": ["Charentais", "Canari"],
        "Orange": ["Navel", "Sanguine", "Valencia"],
        "Papaye": [],
        "Pastèque": ["Rouge", "Jaune"],
        "Pêche": ["Jaune", "Blanche"],
        "Poire": ["Conférence", "William", "Comice"],
        "Pomme": ["Golden", "Granny Smith", "Gala"],
        "Prune": ["Quetsche", "Mirabelle", "Reine-Claude"],
        "Raisin": ["Blanc", "Rouge", "Noir"]
      },
      legume: {
        "Artichaut": [],
        "Asperge": ["Verte", "Blanche", "Violette"],
        "Aubergine": ["Noire", "Blanche", "Graffiti"],
        "Betterave": ["Rouge", "Jaune", "Chioggia"],
        "Brocoli": [],
        "Carotte": ["Nantaise", "Chantenay", "Touchon"],
        "Céleri": ["Branche", "Rave"],
        "Chou": ["Rouge", "Vert", "Fleur"],
        "Concombre": [],
        "Courge": ["Butternut", "Potimarron", "Spaghetti"],
        "Courgette": ["Verte", "Jaune", "Ronde de Nice"],
        "Épinard": ["Géant d'hiver", "Monstrueux de Viroflay", "Butterflay"],
        "Haricot": ["Vert", "Rouge", "Blanc"],
        "Laitue": ["Romaine", "Batavia", "Iceberg"],
        "Navet": ["Blanc", "Jaune", "Rutabaga"],
        "Oignon": ["Jaune", "Rouge", "Blanc"],
        "Patate douce": ["Orange", "Violette"],
        "Poireau": [],
        "Pomme de terre": ["Charlotte", "Bintje", "Ratte"],
        "Radis": ["Rose", "Noir", "Blanc"],
        "Tomate": ["Cœur de Bœuf", "Roma", "Cerise"]
      },
      condiment: {
        "Ail": ["Blanc", "Noir", "Des ours"],
        "Aneth": [],
        "Basilic": ["Vert", "Pourpre"],
        "Ciboulette": [],
        "Coriandre": [],
        "Estragon": [],
        "Menthe": ["Poivrée", "Verte"],
        "Origan": [],
        "Persil": ["Plat", "Frisé"],
        "Romarin": [],
        "Sauge": [],
        "Thym": ["Citron", "Classique"]
      },
      fruitSec: {
        "Amande": [],
        "Cajou": [],
        "Noix": ["Classique", "Pécan"],
        "Noisette": [],
        "Pistache": []
      },
      exotique: {
        "Bissap": [],
        "Carambole": [],
        "Corossol": [],
        "Durian": [],
        "Gombo": [],
        "Jacquier": [],
        "Kiwano": [],
        "Safou": [],
        "Tamarin": [],
        "Ugli": []
      }
    };
